import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        syne: ['Syne', 'sans-serif'],
        dmsans: ['"DM Sans"', 'sans-serif'],
        "label-caps": ["'DM Sans'", "sans-serif"],
        "display-lg": ["Syne", "sans-serif"],
        "body-md": ["'DM Sans'", "sans-serif"],
        "headline-sm": ["Syne", "sans-serif"],
        "headline-md": ["Syne", "sans-serif"],
        "headline-lg": ["Syne", "sans-serif"],
        "body-lg": ["'DM Sans'", "sans-serif"],
        "body-sm": ["'DM Sans'", "sans-serif"],
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "1.4", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }]
      },
      spacing: {
        "lg": "24px",
        "margin-desktop": "48px",
        "sm": "8px",
        "md": "16px",
        "xxl": "64px",
        "gutter": "24px",
        "xl": "40px",
        "unit": "4px",
        "xs": "4px",
        "margin-mobile": "16px"
      },
      colors: {
        "custom-dark-green": "#123e20",
        "custom-sec-green": "#2d6a4f",
        "custom-coral": "#ba1a1a",
        "custom-card-mint": "#d8f3dc",
        "custom-deep-red": "#8b0000",
        "custom-bg": "#f5f1e8",
        "settings-bg": "#F5F1E8",
        "settings-on-bg": "#14291F",
        "settings-primary": "#14291F",
        "settings-secondary": "#2D4A3A",
        "settings-outline": "#D8D2C4",
        "settings-outline-var": "#D8D2C4",
        "settings-surface-dim": "#E8EDE5",
        "settings-surface": "#FFFFFF",
        "settings-success": "#3A5544",
        "settings-error": "#E5484D",
        brand: {
          900: '#1a2e0a',
          800: '#2B4A18',
          600: '#3d6b1e',
          400: '#7AB648',
          50: '#f3f9ea',
          green: '#123e20',
          olive: '#1b4d2c',
          textDark: '#45483C',
          navText: '#121C2A',
          bgLight: '#F8F9FF',
          statsBg: '#EFF4FF',
          btnBlue: '#D9E3F6',
          borderLight: '#C5C8B8',
          glassBg: 'rgba(221, 229, 211, 0.4)',
          glassBorder: 'rgba(199, 210, 192, 0.5)',
        },
        cream: '#F5F2E8',
        // Authentication layout colors
        "on-primary": "#ffffff",
        "secondary-fixed": "#c8f17a",
        "surface-container-low": "#eff4ff",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#bace98",
        "surface": "#f8f9ff",
        "on-secondary-fixed-variant": "#364e00",
        "inverse-on-surface": "#eaf1ff",
        "on-surface": "#121c2a",
        "on-error": "#ffffff",
        "on-surface-variant": "#45483c",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "surface-tint": "#50652a",
        "surface-container": "#e6eeff",
        "on-primary-fixed-variant": "#394d14",
        "surface-container-high": "#dee9fc",
        "primary": "var(--color-primary, #123e20)",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "on-secondary-container": "var(--color-on-secondary-container, #1b4332)",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#131f00",
        "tertiary-fixed": "#d6eab2",
        "surface-dim": "#d0dbed",
        "tertiary": "#415227",
        "inverse-surface": "#27313f",
        "surface-bright": "#f8f9ff",
        "on-tertiary-container": "#d5e9b1",
        "on-tertiary-fixed": "#121f00",
        "primary-fixed-dim": "#b6d088",
        "surface-variant": "#d9e3f6",
        "on-tertiary-fixed-variant": "#3c4c22",
        "on-primary-fixed": "#131f00",
        "primary-fixed": "#d2eca2",
        "outline-variant": "#c5c8b8",
        "inverse-primary": "#b6d088",
        "on-primary-container": "var(--color-on-primary-container, #a3d9b4)",
        "secondary-container": "var(--color-secondary-container, #d8f3dc)",
        "secondary-fixed-dim": "#add461",
        "tertiary-container": "#596a3d",
        "primary-container": "var(--color-primary-container, #1b4d2c)",
        "outline": "#75796b",
        "secondary": "var(--color-secondary, #2d6a4f)",
        "on-background": "#121c2a",
        "surface-container-highest": "#d9e3f6"
      },
    },
  },
  plugins: [],
};

export default config;
