import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        syne: ['Syne', 'sans-serif'],
        dmsans: ['"DM Sans"', 'sans-serif'],
      },
      colors: {
        brand: {
          green: '#3E5219',
          olive: '#556B2F',
          textDark: '#45483C',
          navText: '#121C2A',
          bgLight: '#F8F9FF',
          statsBg: '#EFF4FF',
          btnBlue: '#D9E3F6',
          borderLight: '#C5C8B8',
          glassBg: 'rgba(221, 229, 211, 0.4)',
          glassBorder: 'rgba(199, 210, 192, 0.5)',
        },
        // Authentication layout colors
        "on-primary": "#ffffff",
        "secondary-fixed": "#c8f17a",
        "surface-container-low": "#eff4ff",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#bace98",
        "surface": "#f8f9ff",
        "on-secondary-fixed-variant": "#364e00",
        "inverse-on-surface": "#eaf1ff",
        "on-surface": "#121c2a",
        "on-error": "#ffffff",
        "on-surface-variant": "#45483c",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "surface-tint": "#50652a",
        "surface-container": "#e6eeff",
        "on-primary-fixed-variant": "#394d14",
        "surface-container-high": "#dee9fc",
        "primary": "#3e5219",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "on-secondary-container": "#4e6e00",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#131f00",
        "tertiary-fixed": "#d6eab2",
        "surface-dim": "#d0dbed",
        "tertiary": "#415227",
        "inverse-surface": "#27313f",
        "surface-bright": "#f8f9ff",
        "on-tertiary-container": "#d5e9b1",
        "on-tertiary-fixed": "#121f00",
        "primary-fixed-dim": "#b6d088",
        "surface-variant": "#d9e3f6",
        "on-tertiary-fixed-variant": "#3c4c22",
        "on-primary-fixed": "#131f00",
        "primary-fixed": "#d2eca2",
        "outline-variant": "#c5c8b8",
        "inverse-primary": "#b6d088",
        "on-primary-container": "#d0eba1",
        "secondary-container": "#c8f17a",
        "secondary-fixed-dim": "#add461",
        "tertiary-container": "#596a3d",
        "primary-container": "#556b2f",
        "outline": "#75796b",
        "secondary": "#496800",
        "on-background": "#121c2a",
        "surface-container-highest": "#d9e3f6"
      },
    },
  },
  plugins: [],
}
export default config;
