export const BLOOD_REQUEST_STATUS = {
  PENDING: 'PENDING',
  MATCHING: 'MATCHING',
  DONOR_FOUND: 'DONOR_FOUND',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export const ORGAN_REQUEST_STATUS = {
  PENDING: 'PENDING',
  MATCHING: 'MATCHING',
  DONOR_FOUND: 'DONOR_FOUND',
  UNDER_VERIFICATION: 'UNDER_VERIFICATION',
  APPROVED: 'APPROVED',
  SURGERY_SCHEDULED: 'SURGERY_SCHEDULED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export const AMBULANCE_TRIP_STATUS = {
  REQUESTED: 'REQUESTED',
  ASSIGNED: 'ASSIGNED',
  ON_THE_WAY: 'ON_THE_WAY',
  PICKED_UP: 'PICKED_UP',
  ARRIVED: 'ARRIVED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export type BloodRequestStatus = typeof BLOOD_REQUEST_STATUS[keyof typeof BLOOD_REQUEST_STATUS];
export type OrganRequestStatus = typeof ORGAN_REQUEST_STATUS[keyof typeof ORGAN_REQUEST_STATUS];
export type AmbulanceTripStatus = typeof AMBULANCE_TRIP_STATUS[keyof typeof AMBULANCE_TRIP_STATUS];
